const guide = (why, signal, market, caveat, related) => ({
  why,
  signal,
  market,
  caveat,
  related,
})

export const INDICATOR_GUIDES = {
  '/cpi': guide(
    'Primary read on household inflation and progress toward the BOJ price-stability target.',
    'Separate volatile headline moves from core-core and services momentum.',
    'Persistent services inflation matters more for BOJ normalization than a one-month energy shock.',
    'Annual revisions, changing weights and policy measures can alter category contributions.',
    [{ href: '/tokyo-cpi', label: 'Tokyo CPI' }, { href: '/boj-policy', label: 'BOJ Policy' }],
  ),
  '/tokyo-cpi': guide(
    'Provides an early monthly read on the national CPI release.',
    'Focus on core-core and services breadth, not only the headline rate.',
    'A broad Tokyo acceleration can shift expectations before national CPI is published.',
    'Tokyo weights and local price dynamics differ from the national basket.',
    [{ href: '/cpi', label: 'National CPI' }, { href: '/wages', label: 'Wages' }],
  ),
  '/ppi': guide(
    'Tracks upstream goods and services price pressure before potential consumer pass-through.',
    'Compare domestic CGPI, import prices and SPPI to locate the source of pressure.',
    'Import-led pressure is more FX-sensitive; service-price persistence is more domestically rooted.',
    'Producer-price moves do not pass through one-for-one or at a fixed lag.',
    [{ href: '/yen-transmission', label: 'Yen Transmission' }, { href: '/cpi', label: 'CPI' }],
  ),
  '/boj-policy': guide(
    'Combines wages, demand and underlying inflation into a policy-relevant BOJ framework.',
    'Look for confirmation across the output gap, labor tightness and underlying inflation measures.',
    'A broad, persistent configuration is more policy-relevant than any single monthly series.',
    'Policy rules and scorecards are analytical frameworks, not BOJ forecasts or reaction functions.',
    [{ href: '/wages', label: 'Wages' }, { href: '/cpi', label: 'CPI' }],
  ),
  '/yen-transmission': guide(
    'Shows how exchange-rate moves enter import costs and the domestic inflation pipeline.',
    'Read USD/JPY together with effective exchange rates and import-price momentum.',
    'Persistent yen weakness raises external-cost risk, but margins and contracts shape pass-through.',
    'Co-movement is descriptive and does not establish a stable causal coefficient.',
    [{ href: '/ppi', label: 'Producer Prices' }, { href: '/trade', label: 'Trade' }],
  ),
  '/gdp': guide(
    'The broadest hard-data measure of domestic economic growth and expenditure composition.',
    'Decompose the headline into consumption, investment, government and net exports.',
    'Markets usually respond more to demand composition and revisions than to one annualized headline.',
    'Quarterly GDP is volatile and subject to material revisions.',
    [{ href: '/consumption', label: 'Consumption' }, { href: '/machine-orders', label: 'Machine Orders' }],
  ),
  '/iip': guide(
    'Tracks manufacturing output and the near-term goods cycle.',
    'Compare production with shipments and inventories to identify restocking or excess supply.',
    'A production recovery supported by shipments is stronger than inventory accumulation alone.',
    'JapanPulse currently preserves a labeled reference snapshot because the source identifier is unstable.',
    [{ href: '/tankan', label: 'Tankan' }, { href: '/trade', label: 'Trade' }],
  ),
  '/tsip': guide(
    'Measures activity across service industries that dominate Japan’s economy.',
    'Watch breadth across consumer, business and transport-related services.',
    'Broad service expansion can confirm that growth extends beyond manufacturing.',
    'Sector weights and publication lags differ from GDP service components.',
    [{ href: '/consumption', label: 'Consumption' }, { href: '/watcher', label: 'Economy Watchers' }],
  ),
  '/machine-orders': guide(
    'A leading indicator for private equipment investment six to nine months ahead.',
    'Use the core series and multi-month trend because large orders create monthly noise.',
    'A broad order upturn can reinforce the capex and productivity outlook.',
    'Ships and electric power are excluded; realization can differ from reported orders.',
    [{ href: '/gdp', label: 'GDP' }, { href: '/tankan', label: 'Tankan' }],
  ),
  '/consumption': guide(
    'Shows whether household demand is strengthening after accounting for inflation.',
    'Compare real spending, basic needs and discretionary categories with income growth.',
    'Real discretionary demand is a cleaner cyclical signal than nominal spending alone.',
    'The household survey is volatile and does not cover all forms of consumption.',
    [{ href: '/wages', label: 'Wages' }, { href: '/watcher', label: 'Economy Watchers' }],
  ),
  '/tankan': guide(
    'The BOJ’s flagship survey of business conditions, investment and inflation expectations.',
    'Read levels, change and the large-small firm gap across manufacturing and services.',
    'Capex intentions and pricing plans often matter more than the headline diffusion index alone.',
    'Diffusion indices measure breadth, not the magnitude of output changes.',
    [{ href: '/machine-orders', label: 'Machine Orders' }, { href: '/boj-policy', label: 'BOJ Policy' }],
  ),
  '/watcher': guide(
    'A timely street-level survey of current conditions and the near-term outlook.',
    'Compare current and outlook indices with the neutral level of 50.',
    'A synchronized improvement can lead harder household and service data.',
    'Survey sentiment can react sharply to weather, prices and headlines.',
    [{ href: '/consumption', label: 'Consumption' }, { href: '/tankan', label: 'Tankan' }],
  ),
  '/wages': guide(
    'Wage growth is central to household purchasing power and sustainable BOJ inflation.',
    'Separate nominal, scheduled and real wages; watch whether gains broaden beyond bonuses.',
    'Sustained scheduled-pay growth is more durable than bonus-driven monthly spikes.',
    'Preliminary releases and composition effects can be revised.',
    [{ href: '/labour', label: 'Labor Market' }, { href: '/boj-policy', label: 'BOJ Policy' }],
  ),
  '/labour': guide(
    'Measures labor-market slack, participation and the employment side of domestic demand.',
    'Read unemployment with participation, employment growth and wage pressure.',
    'Low unemployment is supportive only if participation and income quality remain healthy.',
    'Demographics and labor-force composition complicate historical comparisons.',
    [{ href: '/wages', label: 'Wages' }, { href: '/job-ratio', label: 'Job Ratio' }],
  ),
  '/job-ratio': guide(
    'Shows labor demand relative to available applicants and often leads wage pressure.',
    'Watch the level, direction and gap between new and total job openings.',
    'A falling ratio signals cooling demand even before unemployment rises.',
    'Structural mismatch can keep the ratio high without equivalent aggregate wage pressure.',
    [{ href: '/labour', label: 'Labor Market' }, { href: '/wages', label: 'Wages' }],
  ),
  '/trade': guide(
    'Tracks external demand, import costs and the contribution of net trade.',
    'Separate values from volumes and identify country and product concentration.',
    'Export breadth is more informative than a yen-inflated nominal total.',
    'Currency moves and commodity prices can dominate nominal trade values.',
    [{ href: '/yen-transmission', label: 'Yen Transmission' }, { href: '/iip', label: 'Industrial Production' }],
  ),
  '/inbound-tourism': guide(
    'Captures a fast-growing services export and its contribution to regional demand.',
    'Compare arrivals, spending per visitor, accommodation and source-market breadth.',
    'Spending breadth matters more than arrivals alone for the macro contribution.',
    'Capacity constraints, FX and survey-method changes can affect comparisons.',
    [{ href: '/consumption', label: 'Consumption' }, { href: '/trade', label: 'Trade' }],
  ),
  '/us/cpi': guide(
    'The main monthly measure of consumer inflation and a key input to Fed and market pricing.',
    'Compare core momentum, shelter, services and weighted contributions; then inspect base effects.',
    'Persistent weighted categories matter more than a volatile headline surprise.',
    'Scenario paths are mechanical and category contributions are approximate.',
    [{ href: '/us/ppi', label: 'US PPI' }, { href: '/us/consumption', label: 'Core PCE' }],
  ),
  '/us/ppi': guide(
    'Measures pipeline inflation in final demand before consumer-price transmission.',
    'Focus on core ex-food, energy and trade services plus goods-services breadth.',
    'A broad re-acceleration can raise near-term PCE inflation risk.',
    'Trade-services margins and revisions make PPI different from a simple CPI lead.',
    [{ href: '/us/cpi', label: 'US CPI' }, { href: '/us/consumption', label: 'PCE' }],
  ),
  '/us/consumption': guide(
    'Combines the Fed’s preferred inflation gauge with household demand and income capacity.',
    'Compare core PCE momentum, real spending, real income, saving and dining demand.',
    'Spending that persistently outruns income can be strong now but less sustainable later.',
    'Advance retail estimates are revised and real dining sales are an approximation.',
    [{ href: '/us/cpi', label: 'US CPI' }, { href: '/us/rates', label: 'Rates' }],
  ),
  '/us/manufacturing': guide(
    'Sequences early regional surveys into the national ISM manufacturing signal.',
    'Keep months aligned and compare direction rather than raw levels across unlike surveys.',
    'Breadth across new orders and employment is more useful than one regional headline.',
    'Regional indices and ISM use different samples and scales.',
    [{ href: '/us-macro', label: 'US Growth' }, { href: '/us/employment', label: 'Employment' }],
  ),
  '/us/employment': guide(
    'The central monthly read on jobs, unemployment, participation and wage pressure.',
    'Read payroll breadth, unemployment and earnings together; distinguish level from momentum.',
    'Cooling without a sharp rise in layoffs is consistent with rebalancing rather than recession.',
    'Payrolls are revised and survey differences can create temporary divergences.',
    [{ href: '/us/initial-claims', label: 'Initial Claims' }, { href: '/us/jolts', label: 'JOLTS' }],
  ),
  '/us/initial-claims': guide(
    'The highest-frequency official signal of layoffs and labor-market deterioration.',
    'Use the four-week average, continuing claims and historical percentile.',
    'Persistent increases across both initial and continuing claims are more concerning than holiday noise.',
    'Seasonal adjustment and state processing create volatile weekly readings.',
    [{ href: '/us/employment', label: 'Employment' }, { href: '/us/jolts', label: 'JOLTS' }],
  ),
  '/us/jolts': guide(
    'Describes labor demand and worker flows beneath the unemployment rate.',
    'Compare openings, hires, quits and layoffs with the openings-to-unemployed ratio.',
    'Falling openings with stable layoffs points to normalization; rising layoffs signals more acute weakness.',
    'JOLTS is lagged, revised and subject to survey-response uncertainty.',
    [{ href: '/us/employment', label: 'Employment' }, { href: '/us/initial-claims', label: 'Claims' }],
  ),
  '/us/rates': guide(
    'Links the Treasury curve, real yields, inflation pricing and broad financial conditions.',
    'Separate policy expectations, term premium, real rates and breakeven inflation.',
    'Tighter real yields and financial conditions can slow activity even without another Fed hike.',
    'Breakevens include risk and liquidity premia and are not pure inflation forecasts.',
    [{ href: '/us-macro', label: 'Fed Policy' }, { href: '/us/cpi', label: 'US CPI' }],
  ),
  '/us-macro': guide(
    'Connects growth, consumption and policy settings in one US macro framework.',
    'Compare hard growth data with the effective funds rate and policy-rule benchmarks.',
    'The policy stance depends on real rates and the cycle, not only the nominal funds rate.',
    'Taylor-style rules are model illustrations, not forecasts of FOMC decisions.',
    [{ href: '/us/rates', label: 'Rates' }, { href: '/us/consumption', label: 'Consumption' }],
  ),
}

export function indicatorGuideForPath(pathname) {
  return INDICATOR_GUIDES[pathname] ?? null
}
